name: Bug Report
description: Signaler un bug dans le starter
title: "[Bug] "
labels: ["bug"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: Que s'est-il passé ?
      description: Décrivez le bug et comment le reproduire.
    validations:
      required: true
